apiVersion: apps/v1
kind: Deployment
metadata:
  name: fts-indexer
  namespace: collectors
  labels:
    app: fts-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fts-indexer
  template:
    metadata:
      labels:
        app: fts-indexer
    spec:
      containers:
        - name: fts-indexer
          image: ivukotic/fts_indexer:latest
          command: ["python"]
          args: ["FTS_indexer.py"]
          env:
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  name: fts
                  key: mq_user
            - name: MQ_PASS
              valueFrom:
                secretKeyRef:
                  name: fts
                  key: mq_pass
            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  name: fts
                  key: mq_host
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: fts
                  key: es_user
            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: fts
                  key: es_pass
            - name: ES_HOST
              valueFrom:
                secretKeyRef:
                  name: fts
                  key: es_host
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
