name: Build FTS indexer dockerhub image

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
          image: ivukotic/fts_indexer
          dockerfile: Dockerfile
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
          repository: maniaclab/river_apps
          event-type: gitops-fts-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
